services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=mysql+pymysql://root:mysqlpassword@mysql:3306/BalanceScaleApp
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - app-network

  frontend:
    build: ./frontend
    ports:
      - "5173:5173"
    depends_on:
      - backend
    networks:
      - app-network

  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: mysqlpassword
      MYSQL_DATABASE: BalanceScaleApp
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - app-network
    healthcheck:
      test: ["CMD-SHELL", "mysql -uroot -pmysqlpassword -e 'SELECT 1'"]
      interval: 30s
      timeout: 30s
      retries: 20

networks:
  app-network:
    driver: bridge

volumes:
  mysql-data:
